version: '2.1'
# 6/23/2017 - version 3.x does not support extends yet.
# - https://docs.docker.com/compose/extends/#extending-services
services:
  ca_intake:
    build: .
    command: ./bin/docker_start
    ports:
      - "3000:3000"
      - "4857:4857"
    environment:
      RAILS_ENV: ${RAILS_ENV:-development}
      FERB_API_URL: "https://ferbapi.preint.cwds.io"
      DORA_API_URL: "https://doraapi.preint.cwds.io"
      NODE_ENV: development
      AUTHENTICATION_URL: ${AUTHENTICATION_URL:-https://web.preint.cwds.io/perry}
      AUTHENTICATION: ${AUTHENTICATION:-true}
      REDIS_HOST: 'redis'
      REDIS_PORT: 6379
      USE_XVFB: 'true'
      TZ: US/Pacific
    volumes:
      - .:/ca_intake
      - .chromedriver-helper:/root/.chromedriver-helper
      - ca_intake_rubygems:/ruby_gems
      - ca_intake_node_modules:/ca_intake/node_modules
    links:
      - redis
    tty: true
    stdin_open: true
    cap_add:
      - SYS_ADMIN
  redis:
    image: 'redis:3.0'
    ports:
      - "6379:6379"
volumes:
  ca_intake_rubygems:
  ca_intake_node_modules:
