# config/feature.yml
development:
  features:
    authentication: <%= ENV.fetch('AUTHENTICATION', false) %>
    perry_version_two: true
    centralized_sessions: true
    snapshot: true
    screenings: true
    enable_newrelic_analytics: true

test:
  features:
    authentication: false
    perry_version_two: false
    centralized_sessions: true
    snapshot: true
    screenings: true
    enable_newrelic_analytics: true

production:
  features:
    authentication: <%= ENV.fetch('AUTHENTICATION', false) %>
    perry_version_two: <%= ENV.fetch('PERRY_VERSION_TWO', true) %>
    centralized_sessions: <%= ENV.fetch('CENTRALIZED_SESSIONS', false) %>
    snapshot: <%= ENV.fetch('SNAPSHOT', true) %>
    screenings: <%= ENV.fetch('SCREENINGS', true) %>
    enable_newrelic_analytics: <%= ENV.fetch('ENABLE_NEWRELIC_ANALYTICS', true) %>
